### PR TITLE
bubble_sort using javascript

### PR DESCRIPTION
**Pull request by aakash18012**
implementation of bubble sort using Javascript

### CODE REVIEW

**Comment by aakash18012** [comment]
Implementation of bubble sort using Javascript

**Comment by Deepak345** [comment]
Follow specified directory structure conventions.

**Comment by Deepak345** [comment]
Please follow specified directory structure conventions.

**Comment by aakash18012** [comment]
Okay

**Comment by Deepak345** [comment]
You are taking too much time.

**Pull request closed without merging**
